apiVersion: v1
kind: Secret
metadata:
  name: mechanic-secrets
  namespace: mechanic
type: Opaque
data:
  FIREBASE_API_KEY: QUl6YVN5Q0lsblZockpnS2l0NWRsOEY4Q1RXc0FRQmpub1ppTEww
  DAILY_API_KEY: NzQ3NGI0NTEyOTM3YTk2NWEyZjNkMmU5ODYxZGEwNjI3MDYxNjEzODE3ODZmYjM1NmM2ZmIxMmZiYWJhZDUwYw==
